---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pack-build-builder-push
  labels:
    app.kubernetes.io/version: '0.1'
  annotations:
    tekton.dev/pipelines.minVersion: '0.50.0'
    tekton.dev/tags: build, push, builder
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This Pipeline builds a buildpacks builder image using pack client.
  workspaces:
    - name: source-dir
    - name: data-store
    - name: pack-workspace
  params:
    - description: A boolean value used to execute or not a task
      name: debug
      type: string
      default: "false"
    - description: Source Repository URL
      name: git-url
      type: string
    - description: Source directory where code is cloned
      name: source-dir
      type: string
      default: "."
    - description: Pack client image url
      name: imageUrl
      type: string
      default: buildpacksio/pack
    - description: Pack client image tag
      name: imageTag
      type: string
      default: latest
    - description: Name of the Builder image to create
      name: output-image
      type: string
      default: latest
    - description: Pack builder command flags
      name: packCmdBuilderFlags
      type: array
      default: [""]

  tasks:
    - name: git-clone
      # TODO: Check if we could use the git-clone task part of the tekton catalog instead of this one copied from redhat cop project
      taskRef:
        name: git-clone
      params:
        - name: GIT_PROJECT_URL
          value: '$(params.git-url)'
      workspaces:
        - name: source-dir
          workspace: source-dir

    - name: fetch-packconfig-registrysecret
      runAfter:
        - git-clone
      taskSpec:
        steps:
          - image: quay.io/centos/centos:latest
            script: |
              cd /workspace
              pwd
              ls -la data-store
              ls -la pack-workspace
              echo "Copy pack config.toml to $(workspaces.pack-workspace.path)"
              cp $(workspaces.data-store.path)/config.toml $(workspaces.pack-workspace.path)
              
              echo "Copy .dockerconfigjson to $(workspaces.pack-workspace.path)/.docker/config.json"
              mkdir -p $(workspaces.pack-workspace.path)/.docker
              cp $(workspaces.data-store.path)/.dockerconfigjson $(workspaces.pack-workspace.path)/.docker/config.json
      workspaces:
        - name: data-store
          workspace: data-store
        - name: pack-workspace
          workspace: pack-workspace

    - name: list-pack-files
      runAfter:
        - fetch-packconfig-registrysecret
      when:
        - input: $(params.debug)
          operator: in
          values: [ "true" ]
      taskSpec:
        steps:
          - name: list-source-workspace
            image: quay.io/centos/centos:latest
            script: |
                pwd
                ls -la /workspace/pack-workspace
              # echo "List files under: $(workspaces.pack-workspace.path)"
              # ls -la $(workspaces.pack-workspace.path)/

              # ls -la $(workspaces.pack-workspace.path)/.docker/
              # cat $(workspaces.pack-workspace.path)/.docker/config.json

              # echo "List files under: $(workspaces.source-dir.path)"
              # ls -la $(workspaces.source-dir.path)/
      workspaces:
        - name: pack-workspace
          workspace: pack-workspace
      #   - name: source-dir
      #     workspace: source-dir
